[project]
name = "hexsolver-cn-py"
version = "0.7.2"
description = "Game-styled Hexcells Infinite seed and step solver for Windows."
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "onnxruntime",
    "opencv-python-headless",
    "ortools",
    "pillow",
    "PySide6",
    "qtawesome",
    "rapidocr",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
hexsolver_cn = ["assets/ocr_patterns/*.png"]
